#Extracted 4:  What ports are qualified with URIs?

BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://purl.dataone.org/provone/2015/01/15/ontology#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?port_name
WHERE
{  
  ?port_type     (rdf:type|rdfs:subClassOf)*      yw:Port.
  ?port          rdf:type   ?port_type;
                 rdfs:label            ?port_name;
                 yw:filePathTemplate   ?filePath.
  FILTER (?filePath != "")

} ORDER BY ?port_name
