#Query 22: What data are upstream 2 levels from corrected_image?

BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://purl.dataone.org/provone/2015/01/15/ontology#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?up_data_name
WHERE
{    
      ?data        rdf:type           yw:Data ;
                   rdfs:label         "corrected_image".  
    
      ?data        (^yw:writes/^yw:hasOutPort/yw:hasInPort/yw:reads){2}   ?up_data .
      
      ?up_data    rdf:type             yw:Data ;
                    rdfs:label         ?up_data_name .
   
} ORDER BY ?up_data_name
