#  mq11: What program blocks are immediately downstream of calculate_strategy?

BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3c.org/ns/prov#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?down_program_name
WHERE
{   
      ?program       rdf:type             p1:Program ;
                     rdfs:label           "calculate_strategy" .                                        
    
      ?program       (p1:hasOutPort/p1:hasDefaultParam/^p1:hasDefaultParam/^p1:hasInPort)   ?downprogram .
      
      ?downprogram   rdf:type             p1:Program ;
                     rdfs:label           ?down_program_name .
}
