#  mq3:  What are the names of any top-level functions?

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?name
WHERE
{
  ?function     rdf:type            yw:Function ;
                rdfs:label          ?name.
                
  FILTER NOT EXISTS { ?workflow p1:hasSubProgram ?function }
}