#  mq9: How many ports read data simulate_data_collection[frame_number]?

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT (count(distinct ?program) as ?count)
WHERE
{   
  ?program     p1:hasInPort        ?inport .

  ?inport      rdf:type            p1:Port ;
               rdfs:label          "frame_number" .
}
