SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?urivariable_name ?urivariable_value
WHERE
{    
      ?resource         rdf:type        yw:Resource ;
                        rdfs:label      ?resource_name;
                        yw:instantiates  ?channel;
                        yw:hasURIVariable  ?uri_variable.

      ?channel          rdf:type        p1:Channel ;
                        rdfs:label      ?channel_name.  
    
      ?uri_variable    rdf:type         yw:URIVariable ;
                       yw:variableName   ?urivariable_name;
                       yw:variableValue  ?urivariable_value.
      

  FILTER (?channel_name = "raw_image")
   
};