SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?down_channel_name
WHERE
{    
      ?channel        rdf:type           p1:Channel ;
                      rdfs:label         ?channel_name.  
    
      ?channel        (^p1:connectsTo/^p1:hasInPort/p1:hasOutPort/p1:connectsTo){2}   ?down_channel .
      
      ?down_channel    rdf:type             p1:Channel ;
                       rdfs:label           ?down_channel_name .

  FILTER (?channel_name = "energies")
   
} ORDER BY ?down_channel_name ;