#Query 4: (ProgramName) What are the names of the programs comprising the top-level workflow?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://purl.dataone.org/provone/2015/01/15/ontology#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?block_name ?block_description
WHERE
{   ?yw          rdf:type            yw:Workflow;
                 rdfs:label          ?yw_name;
                 yw:hasSubBlock      ?block.

    ?block       rdf:type            yw:Block;
                 rdfs:label          ?block_name;
                 rdfs:comment        ?block_description .

} ORDER BY ?block_name;