#Prov Query 1: Is there a channel between output port collect_data_set[frame_number] and input port transform_images[frame_number]?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://purl.dataone.org/provone/2015/01/15/ontology#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?channel_name
WHERE 
 {    ?block_1       rdf:type               yw:Block ;
                     rdfs:label             "collect_data_set" ;
                     yw:hasOutPort          ?outport.

      ?outport       rdf:type               yw:OutPort;
                     rdfs:label             "frame_number";
                     yw:sends               ?channel.


      ?inport        rdf:type               yw:ParamPort;
                     rdfs:label             "frame_number";
                     yw:receives             ?channel.   
                                             
    
      ?block_2       rdf:type               yw:Block ;
                     rdfs:label             "transform_images";
                     yw:hasInPort           ?inport.
    
      ?channel       rdf:type               yw:Data;
                     rdfs:label             ?channel_name.
       
 };