SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?up_channel_name
WHERE
{    
      ?channel        rdf:type             p1:Channel ;
                      rdfs:label           ?channel_name.   
    
      ?channel        (^p1:connectsTo/^p1:hasOutPort/p1:hasInPort/p1:connectsTo)+   ?up_channel .
      
      ?up_channel    rdf:type            p1:Channel ;
                       rdfs:label        ?up_channel_name .

  FILTER (?channel_name = "raw_image")
   
} ORDER BY ?up_channel_name;