#Query 26: What program blocks are least common upstream block of collect_data_set and log_rejected_sample?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT ?up_first_program_name 
WHERE 
 {    ?first_program       rdf:type             yw:Block ;
                           rdfs:label           "collect_data_set" .                                        
    
      ?first_program      (yw:hasInPort/yw:reads/^yw:writes/^yw:hasOutPort)+   ?up_first_program .
      
      ?up_first_program    rdf:type             yw:Block ;
                           rdfs:label           ?up_first_program_name .

      ?second_program       rdf:type             yw:Block ;
                           rdfs:label            "log_rejected_sample" .                                        
    
      ?second_program      (yw:hasInPort/yw:reads/^yw:writes/^yw:hasOutPort)+   ?up_second_program .
      
      ?up_second_program    rdf:type             yw:Block ;
                           rdfs:label           ?up_second_program_name .
      
      FILTER (?up_second_program_name = ?up_first_program_name)
       
 }
 GROUP BY ?up_first_program_name
 ORDER BY (count(?up_first_program) AS ?distance)
 LIMIT 1;