SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?down_program_name   #Get the direct downstream program name
WHERE 
 {    #get the program with name "calculate_strategy" and put into ?program variable
      ?program       rdf:type             p1:Program ;           
                     rdfs:label           "calculate_strategy" .    
                     
      #get all of the programs immediately connect to ?program (via ?hasOutPort, hasInPort, hasDefaultParam relationsips) 
      #put these programs into ?down_program variable
      ?program      (p1:hasOutPort/p1:connectsTo/^p1:connectsTo/^p1:hasInPort)   ?down_program .
      
      #get names of the down programs
      ?down_program    rdf:type             p1:Program ;
                       rdfs:label           ?down_program_name .
       
 } ORDER BY ?down_program_name;