SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?up_program_name
WHERE 
 {    #get the program with name "transform_images" and put into ?program variable
      ?program       rdf:type             p1:Program ;
                     rdfs:label           "transform_images" .   
                     
      #get all of the programs immediately connect to ?program (via ?hasOutPort, hasInPort, hasDefaultParam relationsips) 
      #put these programs into ?down_program variable 
      #the "+" sign is to run recursive queries.
      ?program      (p1:hasInPort/p1:connectsTo/^p1:connectsTo/^p1:hasOutPort)+   ?up_program .
      
      ?up_program    rdf:type             p1:Program ;
                     rdfs:label           ?up_program_name .
       
 } ORDER BY ?up_program_name;