SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?channel_name ?channel_description
WHERE
{  
  ?port          rdf:type            p1:Port ;
                 rdfs:label          ?port_name;
                 p1:connectsTo       ?channel.

  ?program       rdf:type            p1:Program ;
                 rdfs:label          ?program_name;
                 p1:hasOutPort       ?port .

  ?channel       rdf:type         p1:Channel;
                 rdfs:label      ?channel_name;
                 rdfs:comment    ?channel_description.
                 
                
  FILTER regex(?program_name, "collect_data_set")
} ORDER BY ?channel_name;