#Combined query 04: Print all URI variables names and values that are associated with corrected_image data.

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX prov: <http://www.w3c.org/ns/prov#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?variable_name ?variable_value
WHERE
{    
    ?port              rdf:type        yw:Port ;
                       rdfs:label      ?port_name;
                       yw:connectsTo   ?data .  

    ?data             rdf:type        yw:Data ;
                      rdfs:label      "corrected_image" . 
    
    ?resource       rdf:type     yw:Resource;
                    yw:actualFilePath   ?resource_path;
                    yw:hasURIVariable   ?URIVariable;
                    yw:isGeneratedBy    ?port.
    
    ?URIVariable    rdf:type  yw:URIVariable;
                    yw:variableName    ?variable_name;
                    yw:variableValue   ?variable_value.
   
} ORDER BY ?variable_name;