#Combined query 01: How many resources belong to raw_image data?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT count(?raw_image_resource)
WHERE
{    
    ?raw_image_port     rdf:type        yw:Port ;
                        yw:connectsTo   ?data .  

    ?data              rdf:type        yw:Data ;
                       rdfs:label      "raw_image" . 
    
    ?raw_image_resource       rdf:type     yw:Resource;
                              yw:actualFilePath   ?filePath;
                              yw:hasURIVariable   ?raw_image_URIVariable;
                              yw:isGeneratedBy    ?raw_image_port.
   
};