#Query 16 (UpstreamDataName): What data is immediately upstream of raw_image?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?up_data_name
WHERE
{    
      ?data        rdf:type             yw:Data;
                   rdfs:label           ?data_name.   
    
      ?data        (^yw:connectsTo/^yw:hasOutPort/yw:hasInPort/yw:connectsTo)   ?up_data .
      
      ?up_data         rdf:type            yw:Data ;
                       rdfs:label        ?up_data_name .

  FILTER (?data_name = "raw_image")
   
} ORDER BY ?up_data_name;