#Query 24: What program blocks are downstream 3 levels from load_screening_results?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?down_block_name
WHERE 
 {    
      ?block       rdf:type             yw:Block ;
                     rdfs:label         "load_screening_results" .   
                     
      ?block      (yw:hasOutPort/yw:connectsTo/^yw:connectsTo/^yw:hasInPort){3}  ?down_block .
      
      ?down_block      rdf:type             yw:Block ;
                     rdfs:label           ?down_block_name .
       
 } ORDER BY ?down_block_name;