#Query 19: What URI variables are associated with writes of data simulate_data_collection[corrected_image]

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?variable_name
WHERE
{    
      ?data          rdf:type             yw:Data ;
                     rdfs:label           ?data_name.  
      
      ?port          rdf:type               yw:Port;
                     yw:hasVariableSource   ?variableSource;
                     yw:connectsTo        ?data.
      
      ?variableSource     rdf:type             yw:Data ;
                          rdfs:label           ?variable_name



  FILTER (?data_name = "corrected_image")
   
} ORDER BY ?variable_name ;