#Query 2:  What is the name and description of the top-level workflow?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?yw_name ?yw_description
WHERE
{  

  ?yw            rdf:type            yw:Workflow;
                 rdfs:label          ?yw_name;
                 rdfs:comment        ?yw_description .

};