#Query 10: How many data are read by more than port in workflow simulate_data_collection?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT ?data_name (count(?port) as ?port_count)
WHERE
{  
  ?port      rdf:type         yw:Port;
             rdfs:label       ?port_name;
             yw:connectsTo    ?data.

  ?data      rdf:type        yw:Data;
             rdfs:label      ?data_name;
             rdfs:comment    ?data_description.   
}
GROUP BY ?data_name
HAVING (count(?port) > 1);