#Recon query 2: What samples did the run of the script collect images from?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>

SELECT DISTINCT ?variableValue
WHERE
{    
     ?port      rdf:type         yw:Port;
                rdfs:label       ?port_name;
                yw:connectsTo    ?data.

     ?data      rdf:type         yw:Data;
                rdfs:label      "raw_image";
                rdfs:comment    ?data_description.

     ?resource   rdf:type     yw:Resource;
                 yw:actualFilePath   ?resource_path;
                 yw:isGeneratedBy    ?port;
                 yw:hasURIVariable   ?URIVariable.

     ?URIVariable rdf:type    yw:URIVariable;
                  yw:variableName         "sample_id";
                  yw:variableValue   ?variableValue.

      
   
};

 