#Recon query 4: Where is the raw image from which corrected image run/data/DRT322/DRT322_11000eV_028.img is derived?

SPARQL BASE         <http://yesworkflow.org/0000000000/>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX p1:   <http://dataone.org/ns/provone#>
PREFIX yw:   <http://yesworkflow.org/ns/yesworkflow>
 
SELECT DISTINCT ?filePath
WHERE
{   
    ?raw_image_port     rdf:type        yw:Port ;
                        yw:connectsTo   ?data .  

    ?data             rdf:type        yw:Data ;
                      rdfs:label      "raw_image" . 
    
    ?raw_image_resource       rdf:type     yw:Resource;
                              yw:actualFilePath   ?filePath;
                              yw:hasURIVariable   ?raw_image_URIVariable;
                              yw:isGeneratedBy    ?raw_image_port.

    ?raw_image_URIVariable   rdf:type    yw:URIVariable;
                             yw:variableName   ?raw_image_URIVariableName;
                             yw:variableValue  ?raw_image_URIVariableValue.
    
    ?correct_image_resource    rdf:type     yw:Resource;
                               yw:actualFilePath   "run/data/DRT322/DRT322_11000eV_028.img";
                               yw:hasURIVariable   ?correct_image_URIVariable.

    ?correct_image_URIVariable rdf:type    yw:URIVariable;
                               yw:variableName    ?correct_image_URIVariableName;
                               yw:variableValue   ?correct_image_URIVariableValue.

    FILTER (?correct_image_URIVariableName = ?raw_image_URIVariableName && ?raw_image_URIVariableValue = ?correct_image_URIVariableValue )
    
   
}






                             
        rdf:type                yw:URIVariable ;
        yw:variableName         "sample_id" ;
        yw:variableValue        "DRT322".

    <simulate_data_collection#corrected_image_resource/199/v2>
        rdf:type                yw:URIVariable ;
        yw:variableName         "energy" ;
        yw:variableValue        "11000" .

    <simulate_data_collection#corrected_image_resource/199/v3>
        rdf:type                yw:URIVariable ;
        yw:variableName         "frame_number" ;
        yw:variableValue        "028" .


    <simulate_data_collection#raw_image_resource/199>
    rdf:type                yw:Resource ;
    yw:actualFilePath       "run/raw/q55/DRT322/e11000/image_028.raw" ;
    yw:isGeneratedBy        <simulate_data_collection/collect_data_set#raw_image_port> ;
    yw:hasURIVariable       <simulate_data_collection#raw_image_resource/199/v1> ,
                            <simulate_data_collection#raw_image_resource/199/v2> ,
                            <simulate_data_collection#raw_image_resource/199/v3> ,
                            <simulate_data_collection#raw_image_resource/199/v4> .
    <simulate_data_collection#raw_image_resource/199/v1>
        rdf:type                yw:URIVariable ;
        yw:variableName         "cassette_id" ;
        yw:variableValue        "q55".

    <simulate_data_collection#raw_image_resource/199/v2>
        rdf:type                yw:URIVariable ;
        yw:variableName         "sample_id" ;
        yw:variableValue        "DRT322" .

    <simulate_data_collection#raw_image_resource/199/v3>
        rdf:type                yw:URIVariable ;
        yw:variableName         "energy" ;
        yw:variableValue        "11000" .

    <simulate_data_collection#raw_image_resource/199/v4>
        rdf:type                yw:URIVariable ;
        yw:variableName         "frame_number" ;
        yw:variableValue        "028" .